services:
  iniciador:
    image: ubuntu:22.04
    container_name: ${CONTAINER_PREFIX}.ubuntu
    networks:
      - cupom-fiscal-dev
    cpus: 0.1
    mem_limit: 64M
    volumes:
      - ./pdf-files:/pdf-files
      - ./scripts/load-pending-files.sh:/script.sh
    entrypoint: ["/bin/bash", "/script.sh"]
    

  processador:
    build:
      context: .
      dockerfile: worker_app/Dockerfile
    container_name: ${CONTAINER_PREFIX}.processador
    image: processador-de-cupom-fiscal:latest
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cupom-fiscal-dev
    volumes:
      - ./pdf-files:/app/pdf-files
    cpus: 0.25
    mem_limit: 128M
    restart: always
      

  mysql:
    image: mysql:8.0-debian
    container_name: ${CONTAINER_PREFIX}.mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cupom-fiscal-dev
    cpus: 0.3
    mem_limit: 256M


  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: ${CONTAINER_PREFIX}.phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
      PMA_USER: '${MYSQL_USER}'
      PMA_PASSWORD: '${MYSQL_PASSWORD}'
      PMA_ARBITRARY: 1
    depends_on:
      mysql:
        condition: service_healthy  
    networks:
      - cupom-fiscal-dev
    cpus: 0.25
    mem_limit: 128M


networks:
  cupom-fiscal-dev:
    driver: bridge